#!/usr/bin/groovy
@Library('github.com/leonard-waters/jenkins-pipeline@pipeline-v2')
def utils = new com.activedisclosure.Utils()

nodejsTemplate {
  stage('checkout source code') {
    checkout scm
  }

  stage('install dependencies') {
    container('nodejs-build') {
      sh 'yarn version --no-git-tag-version'
      sh 'yarn install;'
    }
  }

  stage('lint') {
    try {
      sh 'yarn lint -f junit -o lint-report.xml'
    } finally {
      junit 'lint-report.xml'
    }
  }

  stage('test') {
    try {
      sh 'yarn add jest jest-junit --dev'
      withEnv(["JEST_JUNIT_OUTPUT=./jest-test-results.xml"]) {
				sh 'yarn test --ci --testResultsProcessor="jest-junit"'
			}
    } finally {
      junit 'unit-test-report.xml'
    }
  }

  stage('build release') {
    sh 'webpack --config webpack.prod.js --bail --display-error-details'
  }

  stage('validate helm chart') {
    def version_tag = tags.get(0)
    
    helmValidate(config, version_tag)
  }

  stage('docker build and publish') {
    dockerBuildAndPublish(config, tags, acct)
  }

  if(util.isCD()) {
    //This requires a user to manually approve to deploy to prod, if no action 
    // is taken after ten minutes the input step times out and the pipeline fails
    stage('approve to production ') {
      approval {
        message = 'Deploy to production?'
        okText = 'Deploy'
        timeoutTime = 10
      }
    }
    
    stage('deploy to production') {
      def version_tag = tags.get(0)
      standardRelease(config, version_tag) {}
    }
  }
}
